### ISSUE TITLE
Bug报告：画图功能生成的图片，点击后会跳转到错误的URL & 其他

### ISSUE THREAD

**Issue by lwd-temp** [jianjianai/NewBingGoGo-Web#2]
![image](https://user-images.githubusercontent.com/26019675/234029250-37050c2d-8d9d-4717-b26d-d34c306273ff.png)

点击图片的跳转链接为`../GeneratePicture/img.html?createmessage=a+moon（后续省略）`，实际上，源码中无此页面，与预期功能不符。

其他的问题：

提交记录中仍有cookie泄露，参考[本文](https://docs.github.com/zh/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository)可以彻底删除。

有点好奇，`nasapod128x128.png`中的pony是您的OC吗？

拼写错误，所有的GTP需要改为GPT。

**Comment by jianjianai** [comment]
图片链接不正确的问题已经修复。
