### ISSUE TITLE
提示：User needs to solve CAPTCHA to continue. 发生未知错误！

### ISSUE THREAD

**Issue by Lancenas** [jianjianai/NewBingGoGo-Web#21]
提示：User needs to solve CAPTCHA to continue. 发生未知错误！

**Comment by jinyulaiguo** [comment]
![image](https://github.com/jianjianai/NewBingGoGo-Web/assets/15800828/122ef6bc-516c-409d-aa77-4bb4cd7c1644)

**Comment by liuliansp** [comment]
这个是newbing 需要人机验证，用edge登录下newbing 验证一下才行

**Comment by jianjianai** [comment]
![image](https://github.com/jianjianai/NewBingGoGo-Web/assets/131033097/715dcbe2-544d-4cd0-bfe3-6a5ca6a8b8be)
这个功能在安排中了

**Comment by jianjianai** [comment]
已经添输入验证码的功能。
