### ISSUE TITLE
Request is throttled. 24消息请求数达到了限制！

### ISSUE THREAD

**Issue by d1h1r1** [jianjianai/NewBingGoGo-Web#24]
这是什么原因

**Comment by jinyulaiguo** [comment]
![image](https://github.com/jianjianai/NewBingGoGo-Web/assets/15800828/ad2deb57-4f41-49c6-9855-604a81b8415b)

**Comment by d1h1r1** [comment]
是的，显示这个，我还没开始用

**Comment by d1h1r1** [comment]
![image](https://github.com/jianjianai/NewBingGoGo-Web/assets/103206466/9545a34b-3356-4400-9559-20b5975bb443)
