### ISSUE TITLE
特性请求：可选是否启用统计脚本

### ISSUE THREAD

**Issue by lwd-temp** [jianjianai/NewBingGoGo-Web#42]
https://github.com/jianjianai/NewBingGoGo-Web/blob/master/src/main/resources/web/js/other/stats.js

（开源库里放一个混淆过的js是不是不太合适？）

**Comment by lwd-temp** [comment]
具体的实现可以是，在后端转发文件时根据用户配置将`stats.js`内容替换为无害的`console.log()`

**Comment by jianjianai** [comment]
这个js文件来自百度统计，不会收集用户隐私信息只用于统计访问量，如果不希望加入统计可以在HTML中将其删除。后续有时间我会加一个配置文件，可选择关闭。

**Comment by jianjianai** [comment]
已经添加对应的配置选项，可关闭统计。
