### ISSUE TITLE
Workers版本不工作是已知问题

### ISSUE THREAD

**Issue by lwd-temp** [jianjianai/NewBingGoGo-Web#56]
`/turing/conversation/create`返回`{"conversationId":"51D|BingProdUnAuthenticatedUsers|15B622DD41A13557B01D5C3A7707BAFA09DBBE083DCD2B7D031C461F4E781D7F","clientId":"985155485310705","conversationSignature":"rQZdWw/w9uCUUtm5Ywpd1DZRoO8HkOUFVXYXHI1MAjU=","result":{"value":"Success","message":null}}`，但`/sydney/ChatHub`没有回应。

我的Workers部署也发生此问题。

**Comment by lwd-temp** [comment]
https://chat.jja8.cn/ 可以返回`{"type":2,"invocationId":"1","item":{"firstNewMessageIndex":null,"defaultChatName":null,"conversationId":"51D|BingProd|E692067E5344C3AC04D5FAA9A0F820EB2D7993D67BCD7945E03E27C190A1072E","requestId":"758ab43c-9c32-4654-80f7-3b0699fb703e","telemetry":{"metrics":null,"startTime":"2023-05-23T12:48:27.7411913Z"},"result":{"value":"Throttled","message":"Request is throttled.","error":"Request is throttled.","serviceVersion":"20230522.41"}}}{"type":3,"invocationId":"1"}` Request is throttled.

但https://bingweb.jja8.cn/ 完全没有反应。

**Comment by lwd-temp** [comment]
在11h前，有报告`sydney.bing.com`的`/sydney/ChatHub`接口无法从中国直连（中国IP报连接403），这可能会影响未完整代理所有连接的浏览器扩展用户。

**Comment by jianjianai** [comment]
因为cloudflare worker无法修改WebSocket协议升级前的http时的请求头，所以是废了一半了。插件可以继续使用cloudflare worker作为魔法链接。但是由cloudflare worker搭建的web站点无法使用，插件的魔法聊天无法使用。

**Comment by sffxzzp** [comment]
> 因为cloudflare worker无法修改WebSocket协议升级前的http时的请求头，所以是废了一半了。插件可以继续使用cloudflare worker作为魔法链接。但是由cloudflare worker搭建的web站点无法使用，插件的魔法聊天无法使用。

有没有试过在 cf workers 里使用 node.js 的 websocket 包？不过这样就无法直接复制粘贴部署了。

**Comment by lwd-temp** [comment]
> > 因为cloudflare worker无法修改WebSocket协议升级前的http时的请求头，所以是废了一半了。插件可以继续使用cloudflare worker作为魔法链接。但是由cloudflare worker搭建的web站点无法使用，插件的魔法聊天无法使用。
> 
> 有没有试过在 cf workers 里使用 node.js 的 websocket 包？不过这样就无法直接复制粘贴部署了。
> 
> 参考：https://developers.cloudflare.com/workers/runtime-apis/nodejs/ https://github.com/websockets/ws/blob/master/lib/websocket.js#L52

这个项目或许有参考价值？

https://github.com/adams549659584/go-proxy-bingai/blob/master/cloudflare/worker.js

**Comment by lwd-temp** [comment]
已修复
