### ISSUE TITLE
cloudflare workers部署后的后缀能否不增加跳转?

### ISSUE THREAD

**Issue by bernardatgh** [jianjianai/NewBingGoGo-Web#6]
感谢作者的部署和配置,请问下,是否可以直接在页面做版权或其他部署,而不要在域名地址栏"workers domain**### /web/NewBingGoGo.html**"增加这个尾巴"/web/NewBingGoGo.html"做跳转,是否可以不设置?谢谢

**Comment by jianjianai** [comment]
这个是不行的，必须要加这个才能正常运行。
