### ISSUE TITLE
java版本 cookies读取异常？按快速入门配置的

### ISSUE THREAD

**Issue by wintrue** [jianjianai/NewBingGoGo-Web#8]
cookies: 
    ...
    - _U=1w7djTOUYWY2_bME6URBm5Jo.....
    ...

读取时出错！原因：java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap'

**Comment by panpanaw** [comment]
配置文件格式 yaml
可以自行百度学习

**Comment by panpanaw** [comment]
cookies是yaml文件中的列表格式
~~~ yaml
cookies:
 - 第1条
 - 第2条
 - 第3条
~~~

**Comment by wintrue** [comment]
thanks
